In [2]:
import pandas as pd
import numpy as nd 
import matplotlib.pyplot as mb
from sklearn import tree,metrics

In [3]:
df=pd.read_csv("penguins_size.csv")

In [4]:
df

    species     island  ...  body_mass_g     sex
0    Adelie  Torgersen  ...       3750.0    MALE
1    Adelie  Torgersen  ...       3800.0  FEMALE
2    Adelie  Torgersen  ...       3250.0  FEMALE
3    Adelie  Torgersen  ...          NaN     NaN
4    Adelie  Torgersen  ...       3450.0  FEMALE
..      ...        ...  ...          ...     ...
339  Gentoo     Biscoe  ...          NaN     NaN
340  Gentoo     Biscoe  ...       4850.0  FEMALE
341  Gentoo     Biscoe  ...       5750.0    MALE
342  Gentoo     Biscoe  ...       5200.0  FEMALE
343  Gentoo     Biscoe  ...       5400.0    MALE

[344 rows x 7 columns]

In [5]:
df.describe(
    
)

       culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
count        342.000000       342.000000         342.000000   342.000000
mean          43.921930        17.151170         200.915205  4201.754386
std            5.459584         1.974793          14.061714   801.954536
min           32.100000        13.100000         172.000000  2700.000000
25%           39.225000        15.600000         190.000000  3550.000000
50%           44.450000        17.300000         197.000000  4050.000000
75%           48.500000        18.700000         213.000000  4750.000000
max           59.600000        21.500000         231.000000  6300.000000

In [6]:
df.isnull().sum()

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [7]:
df["culmen_length_mm"].mean()

np.float64(43.9219298245614)

In [8]:
df["culmen_length_mm"]=df["culmen_length_mm"].fillna(df["culmen_length_mm"].mean())

In [9]:
df["culmen_length_mm"]

0      39.10000
1      39.50000
2      40.30000
3      43.92193
4      36.70000
         ...
339    43.92193
340    46.80000
341    50.40000
342    45.20000
343    49.90000
Name: culmen_length_mm, Length: 344, dtype: float64

In [10]:
df["culmen_depth_mm"]=df["culmen_depth_mm"].fillna(df["culmen_depth_mm"].mean())

In [11]:
df["flipper_length_mm"]=df["flipper_length_mm"].fillna(df["flipper_length_mm"].mean())

In [12]:
df["body_mass_g"]=df["body_mass_g"].fillna(df["body_mass_g"].median())

In [13]:
df

    species     island  ...  body_mass_g     sex
0    Adelie  Torgersen  ...       3750.0    MALE
1    Adelie  Torgersen  ...       3800.0  FEMALE
2    Adelie  Torgersen  ...       3250.0  FEMALE
3    Adelie  Torgersen  ...       4050.0     NaN
4    Adelie  Torgersen  ...       3450.0  FEMALE
..      ...        ...  ...          ...     ...
339  Gentoo     Biscoe  ...       4050.0     NaN
340  Gentoo     Biscoe  ...       4850.0  FEMALE
341  Gentoo     Biscoe  ...       5750.0    MALE
342  Gentoo     Biscoe  ...       5200.0  FEMALE
343  Gentoo     Biscoe  ...       5400.0    MALE

[344 rows x 7 columns]

In [14]:
df["sex"].value_counts()

sex
MALE      168
FEMALE    165
.           1
Name: count, dtype: int64

In [15]:
df["sex"]=df["sex"].replace(".","MALE")

In [16]:
df["sex"]

0        MALE
1      FEMALE
2      FEMALE
3         NaN
4      FEMALE
        ...
339       NaN
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 344, dtype: object

In [17]:
df["sex"]=df['sex'].fillna("MALE")

In [18]:
df["sex"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 344 entries, 0 to 343
Series name: sex
Non-Null Count  Dtype
--------------  -----
344 non-null    object
dtypes: object(1)
memory usage: 2.8+ KB

In [19]:
df["species"].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [20]:
df["species"]=df["species"].replace({"Adelie":0,"Gentoo":1,"Chinstrap":2})

C:\Users\Goutham\AppData\Local\Temp\ipykernel_4108\4239004730.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["species"]=df["species"].replace({"Adelie":0,"Gentoo":1,"Chinstrap":2})

In [21]:
df["species"]

0      0
1      0
2      0
3      0
4      0
      ..
339    1
340    1
341    1
342    1
343    1
Name: species, Length: 344, dtype: int64

In [22]:
df["sex"].value_counts()

sex
MALE      179
FEMALE    165
Name: count, dtype: int64

In [23]:
df["island"]=df["island"].replace({"Biscoe":0,"Dream":1,"Torgersen":2})

C:\Users\Goutham\AppData\Local\Temp\ipykernel_4108\3503784213.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["island"]=df["island"].replace({"Biscoe":0,"Dream":1,"Torgersen":2})

In [24]:
df["sex"]=df["sex"].replace({"MALE":0,"FEMALE":1})

C:\Users\Goutham\AppData\Local\Temp\ipykernel_4108\1367413559.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["sex"]=df["sex"].replace({"MALE":0,"FEMALE":1})

In [25]:
df

     species  island  culmen_length_mm  ...  flipper_length_mm  body_mass_g  sex
0          0       2          39.10000  ...         181.000000       3750.0    0
1          0       2          39.50000  ...         186.000000       3800.0    1
2          0       2          40.30000  ...         195.000000       3250.0    1
3          0       2          43.92193  ...         200.915205       4050.0    0
4          0       2          36.70000  ...         193.000000       3450.0    1
..       ...     ...               ...  ...                ...          ...  ...
339        1       0          43.92193  ...         200.915205       4050.0    0
340        1       0          46.80000  ...         215.000000       4850.0    1
341        1       0          50.40000  ...         222.000000       5750.0    0
342        1       0          45.20000  ...         212.000000       5200.0    1
343        1       0          49.90000  ...         213.000000       5400.0    0

[344 rows x 7 columns]

In [26]:
x=df.drop("sex",axis=1)
y=df['sex']

In [27]:
x[0:10]

   species  island  ...  flipper_length_mm  body_mass_g
0        0       2  ...         181.000000       3750.0
1        0       2  ...         186.000000       3800.0
2        0       2  ...         195.000000       3250.0
3        0       2  ...         200.915205       4050.0
4        0       2  ...         193.000000       3450.0
5        0       2  ...         190.000000       3650.0
6        0       2  ...         181.000000       3625.0
7        0       2  ...         195.000000       4675.0
8        0       2  ...         193.000000       3475.0
9        0       2  ...         190.000000       4250.0

[10 rows x 6 columns]

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [29]:
y_train

49     0
310    1
325    0
122    1
167    0
      ..
323    0
192    0
117    0
47     0
172    1
Name: sex, Length: 275, dtype: int64

In [30]:
y_test[0:10]

141    0
6      1
60     1
249    0
54     1
312    1
126    1
215    0
252    1
100    1
Name: sex, dtype: int64

In [31]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()
tree.fit(x_train,y_train)

DecisionTreeClassifier()

In [32]:
y_pred=tree.predict(x_test)

In [33]:
y_pred[1:10]

array([0, 1, 0, 1, 1, 1, 0, 1, 1])

In [34]:
y_train

49     0
310    1
325    0
122    1
167    0
      ..
323    0
192    0
117    0
47     0
172    1
Name: sex, Length: 275, dtype: int64

In [35]:
from sklearn.metrics import accuracy_score
test_acc=accuracy_score(y_test,y_pred)

In [36]:
print("accuracy_score",test_acc)

accuracy_score 0.8405797101449275

In [37]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[30  6]
 [ 5 28]]

In [38]:
import pickle

In [39]:
with open('pen_model.pkl','wb')as file:
    pickle.dump(tree,file)